"""Initial schema for postgres

Revision ID: 48d92e92372c
Revises: 
Create Date: 2026-03-04 16:36:52.921292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d92e92372c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inverters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inverters_id'), 'inverters', ['id'], unique=False)
    op.create_index(op.f('ix_inverters_name'), 'inverters', ['name'], unique=False)
    op.create_index(op.f('ix_inverters_serial_number'), 'inverters', ['serial_number'], unique=True)
    op.create_table('oidc_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('discovery_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_settings_id'), 'oidc_settings', ['id'], unique=False)
    op.create_index(op.f('ix_oidc_settings_provider_name'), 'oidc_settings', ['provider_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inverter_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flg', sa.Integer(), nullable=True),
    sa.Column('tmp', sa.Float(), nullable=True),
    sa.Column('fac', sa.Float(), nullable=True),
    sa.Column('pac', sa.Float(), nullable=True),
    sa.Column('sac', sa.Float(), nullable=True),
    sa.Column('qac', sa.Float(), nullable=True),
    sa.Column('eto', sa.Float(), nullable=True),
    sa.Column('etd', sa.Float(), nullable=True),
    sa.Column('hto', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('wan', sa.Integer(), nullable=True),
    sa.Column('err', sa.Integer(), nullable=True),
    sa.Column('vac1', sa.Float(), nullable=True),
    sa.Column('vac2', sa.Float(), nullable=True),
    sa.Column('vac3', sa.Float(), nullable=True),
    sa.Column('iac1', sa.Float(), nullable=True),
    sa.Column('iac2', sa.Float(), nullable=True),
    sa.Column('iac3', sa.Float(), nullable=True),
    sa.Column('vpv1', sa.Float(), nullable=True),
    sa.Column('vpv2', sa.Float(), nullable=True),
    sa.Column('ipv1', sa.Float(), nullable=True),
    sa.Column('ipv2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inverter_id'], ['inverters.id'], ),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    
    # Create hypertable for metrics
    op.execute("SELECT create_hypertable('metrics', 'timestamp');")

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oidc_settings_provider_name'), table_name='oidc_settings')
    op.drop_index(op.f('ix_oidc_settings_id'), table_name='oidc_settings')
    op.drop_table('oidc_settings')
    op.drop_index(op.f('ix_inverters_serial_number'), table_name='inverters')
    op.drop_index(op.f('ix_inverters_name'), table_name='inverters')
    op.drop_index(op.f('ix_inverters_id'), table_name='inverters')
    op.drop_table('inverters')
    # ### end Alembic commands ###
